### ISSUE TITLE
crash: resolving end() iterator

### ISSUE THREAD

**Issue by Agile86** [strozfriedberg/liblightgrep#8]
https://github.com/strozfriedberg/liblightgrep/blob/master/include/vectorfamily.h

line 232:
`return &*Store[l.What].end();`

line 243:
`return &*Store[l.What].end();`

The crash occurred while resolving end()...

>  	lightgrep-wrapper-msvc.exe!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator*() Line 43	C++
 	lightgrep-wrapper-msvc.exe!VectorFamily<unsigned int>::end(const VectorFamily<unsigned int>::Holder & l) Line 243	C++
 	lightgrep-wrapper-msvc.exe!Graph<Properties,Glushkov,Empty,VectorFamily>::outVertices(unsigned int head) Line 225	C++
 	lightgrep-wrapper-msvc.exe!NFAOptimizer::removeNonMinimalLabels(Graph<Properties,Glushkov,Empty,VectorFamily> & g) Line 344	C++
 	lightgrep-wrapper-msvc.exe!NFAOptimizer::labelGuardStates(Graph<Properties,Glushkov,Empty,VectorFamily> & g) Line 258	C++
 	lightgrep-wrapper-msvc.exe!FSMThingy::finalizeGraph(bool determinize) Line 62	C++
 	lightgrep-wrapper-msvc.exe!create_program(FSMHandle * hFsm, const LG_ProgramOptions * opts) Line 326	C++
 	lightgrep-wrapper-msvc.exe!lg_create_program::__l2::<lambda>() Line 335	C++
 	lightgrep-wrapper-msvc.exe!trapWithRetval<ProgramHandle * <lambda>(void) >(lg_create_program::__l2::ProgramHandle * <lambda>(void) && func, ProgramHandle * fail) Line 54	C++
 	lightgrep-wrapper-msvc.exe!lg_create_program(FSMHandle * hFsm, const LG_ProgramOptions * options) Line 338	C++
 	lightgrep-wrapper-msvc.exe!finder::LightGrep::setup(const std::list<finder::PatternDef,std::allocator<finder::PatternDef> > & patterns, const std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > & default_encodings, const LG_ProgramOptions & prog_opts) Line 83	C++
>	lightgrep-wrapper-msvc.exe!LightGrepTest_RegexWideHexCharacters_Test::TestBody() Line 115	C++

As a workaround:
`return begin(l) + Store[l.What].size();`

**Comment by uckelman-sf** [comment]
Fixed as of  ed42d6c00.
