### ISSUE TITLE
configure-Error 

### ISSUE THREAD

**Issue by mobab-th** [strozfriedberg/liblightgrep#9]
...
checking for bison... bison -y
checking if bison is the parser generator... yes
bison version is... bison (GNU Bison) 3.4.2
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ICU... yes
checking whether C++ compiler accepts -DU_USING_ICU_NAMESPACE=0... yes
checking whether C++ compiler accepts -DU_CHARSET_IS_UTF8=1... yes
checking whether C++ compiler accepts -DUNISTR_FROM_CHAR_EXPLICIT=explicit... yes
checking whether C++ compiler accepts -DUNSTR_FROM_STRING_EXPLICIT=explicit... yes
checking for boostlib >= 1.49.0... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the library!

Tested unter Ubuntu 18.04LTS and Debian Testing.
All Dependencies should be installed.

**Comment by sf-jonstewart** [comment]
It's still referring to Boost::Program_Options. This line:
`checking whether the Boost::Program_Options library is available... yes`
means that `configure` is able to find the Boost program_options headers. From there, it tries to link with `libboost_program_options` to ensure the _library_ is present, too. The error message can be found in `m4/ax_boost_program_options.m4` and appears to indicate that the library could not be found by the linker.

Can you:
1. Let us know the full command-line you're passing to `configure`?

2. Tell us where `libboost_program_options.*` is on your system?

**Comment by mobab-th** [comment]
i've started _configure_ without Parameters.

This solved the problem
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu

Many Thanks!
